collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.21801612386479974
color:
  saturation: 0.6415370763279498
  brandStrength: 0.660217319149524
  lightness: 0.7776316720992327
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  rhythmicContrast: 0.9145258779171854
layout_spectrum: 0.2849835427477956
name: Melba
